Traceback (most recent call last):
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from IPython.core.display import HTML
import pydae.svg_tools as svgt
%config InlineBackend.figure_format = 'svg'
plt.ion()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-1-c48816ed7158>[0m in [0;36m<module>[1;34m[0m
[0;32m      2[0m [1;32mimport[0m [0mmatplotlib[0m[1;33m.[0m[0mpyplot[0m [1;32mas[0m [0mplt[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;32mfrom[0m [0mIPython[0m[1;33m.[0m[0mcore[0m[1;33m.[0m[0mdisplay[0m [1;32mimport[0m [0mHTML[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 4[1;33m [1;32mimport[0m [0mpydae[0m[1;33m.[0m[0msvg_tools[0m [1;32mas[0m [0msvgt[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      5[0m [0mget_ipython[0m[1;33m([0m[1;33m)[0m[1;33m.[0m[0mrun_line_magic[0m[1;33m([0m[1;34m'config'[0m[1;33m,[0m [1;34m"InlineBackend.figure_format = 'svg'"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m [0mplt[0m[1;33m.[0m[0mion[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'pydae.svg_tools'
ModuleNotFoundError: No module named 'pydae.svg_tools'

